export const experiencesContents = [
    { title: 'Experiência 1',
      content: '1Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi purus tortor, consectetur et varius sed, pulvinar sed tortor. Aliquam luctus ac justo id porttitor. Duis sollicitudin sit amet quam id tempus. Nam blandit molestie hendrerit. Fusce eu tincidunt ligula. Phasellus egestas sodales elit quis feugiat. Phasellus rutrum sem lacus, in posuere mauris tempor a. Ut elementum aliquam nulla vitae fringilla. Proin sed nisi ullamcorper, ullamcorper arcu eu, ornare enim. Nullam pretium vehicula arcu consequat consectetur. Vestibulum iaculis, massa eget lacinia sodales, metus dolor faucibus ligula, quis ultricies erat arcu non velit. Integer elementum leo at facilisis bibendum. '
    },
    { title: 'Experiência 2',
      content: '2Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi purus tortor, consectetur et varius sed, pulvinar sed tortor. Aliquam luctus ac justo id porttitor. Duis sollicitudin sit amet quam id tempus. Nam blandit molestie hendrerit. Fusce eu tincidunt ligula. Phasellus egestas sodales elit quis feugiat. Phasellus rutrum sem lacus, in posuere mauris tempor a. Ut elementum aliquam nulla vitae fringilla. Proin sed nisi ullamcorper, ullamcorper arcu eu, ornare enim. Nullam pretium vehicula arcu consequat consectetur. Vestibulum iaculis, massa eget lacinia sodales, metus dolor faucibus ligula, quis ultricies erat arcu non velit. Integer elementum leo at facilisis bibendum. '
    },
    { title: 'Experiência 3',
      content: '3Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi purus tortor, consectetur et varius sed, pulvinar sed tortor. Aliquam luctus ac justo id porttitor. Duis sollicitudin sit amet quam id tempus. Nam blandit molestie hendrerit. Fusce eu tincidunt ligula. Phasellus egestas sodales elit quis feugiat. Phasellus rutrum sem lacus, in posuere mauris tempor a. Ut elementum aliquam nulla vitae fringilla. Proin sed nisi ullamcorper, ullamcorper arcu eu, ornare enim. Nullam pretium vehicula arcu consequat consectetur. Vestibulum iaculis, massa eget lacinia sodales, metus dolor faucibus ligula, quis ultricies erat arcu non velit. Integer elementum leo at facilisis bibendum. '
    },
    { title: 'Experiência 4',
      content: '4orem ipsum dolor sit amet, consectetur adipiscing elit. Morbi purus tortor, consectetur et varius sed, pulvinar sed tortor. Aliquam luctus ac justo id porttitor. Duis sollicitudin sit amet quam id tempus. Nam blandit molestie hendrerit. Fusce eu tincidunt ligula. Phasellus egestas sodales elit quis feugiat. Phasellus rutrum sem lacus, in posuere mauris tempor a. Ut elementum aliquam nulla vitae fringilla. Proin sed nisi ullamcorper, ullamcorper arcu eu, ornare enim. Nullam pretium vehicula arcu consequat consectetur. Vestibulum iaculis, massa eget lacinia sodales, metus dolor faucibus ligula, quis ultricies erat arcu non velit. Integer elementum leo at facilisis bibendum. '
    },
    { title: 'Experiência 5',
      content: '5Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi purus tortor, consectetur et varius sed, pulvinar sed tortor. Aliquam luctus ac justo id porttitor. Duis sollicitudin sit amet quam id tempus. Nam blandit molestie hendrerit. Fusce eu tincidunt ligula. Phasellus egestas sodales elit quis feugiat. Phasellus rutrum sem lacus, in posuere mauris tempor a. Ut elementum aliquam nulla vitae fringilla. Proin sed nisi ullamcorper, ullamcorper arcu eu, ornare enim. Nullam pretium vehicula arcu consequat consectetur. Vestibulum iaculis, massa eget lacinia sodales, metus dolor faucibus ligula, quis ultricies erat arcu non velit. Integer elementum leo at facilisis bibendum. '
    }
  ]